### ISSUE TITLE
Himawari8

### ISSUE THREAD

**Issue by ZL1LAC** [ZbychuButItWasTaken/Overlay#1]
Any chance to add Himawari8 support?

**Comment by ZL1LAC** [comment]
@ZbychuButItWasTaken I know you're busy but just wanna check in and see if you have had time to do this?

**Comment by sp5ews** [comment]
Oh! Honestly, in all the things I forgot about this one! What exactly do you need for Himawari? I made the program as universal and I think it should work out-of-the-box for it. Though I guess it can use some other file format

**Comment by ZL1LAC** [comment]
Let me whip up a few images and I'll show you, stand by.

**Comment by ZL1LAC** [comment]
Decided to get find the image online, as you can see the background is white, but with the other images it processes they blend in with a black background

![image](https://user-images.githubusercontent.com/909007/121702269-d7d1a000-cb25-11eb-91cd-4f8c5b5cfab8.png)

**Comment by sp5ews** [comment]
Ah, well.. that's because the header and footer are set to black by default and himawari images are inverted, but by the looks of it (unlike most other sats) they are not cropped. Pretty easy to get around that tho! I can either add recognition of himawari images by filename, or add a flag to the command. I think making it switchable for all sats is a good idea, but I'll let you decide

**Comment by sp5ews** [comment]
(you could also just edit the color values in the code)

**Comment by ZL1LAC** [comment]
> Ah, well.. that's because the header and footer are set to black by default and himawari images are inverted, but by the looks of it (unlike most other sats) they are not cropped. Pretty easy to get around that tho! I can either add recognition of himawari images by filename, or add a flag to the command. I think making it switchable for all sats is a good idea, but I'll let you decide

Whatever is easy for you.

> (you could also just edit the color values in the code)

To get it to have the black background?  How would I do that?

**Comment by sp5ews** [comment]
Ah wait, I misunderstood you a bit. I though you wanted to make the header & footer match the background.
 This script won't be able to change the background of your image; the background will have to stay white (it's just a side effect of the processing done before using this script. It only adds the header and footer and the best you could do is just change the color of that

**Comment by ZL1LAC** [comment]
Oh ok, I guess it's not that bad in white.
